### PR TITLE
Fix reading point triple real

### PR DESCRIPTION
**Pull request by lgrzywac**
There is an issue with reading RealTriple.
`internal static DxfXDataItem FromBuffer(DxfCodePairBufferReader buffer)` method does `buffer.Advance()` before reading 3 real values, then the `Advance()` method is called 3 times in `private static DxfPoint ReadPoint(DxfCodePair xCoord, DxfCodePairBufferReader buffer, int expectedFirstCode)`. It may cause 2 issues: either wrong data is read or casting string to double occurs.
For example:
```
(...)
1010
3.1
1020
4.2
1030
5.3
1002
}
```

`1010` starts real triple, but as buffer is advanced the`ReadPoint` method tries to set:
```
X=4.2
Y=5.3
Z=}
```

The fix in this pull request fixes the issue by passing to `ReadPoint` method already read `DxfCodePair` from buffer and only 2 items are read inside `ReadPoint` from buffer.

I've splitted the fix into 2 commits. Firs commit contains new test for reading RealTriple (it fails, as the production code is not fixed here) while the second introduces the fix.

### CODE REVIEW

**Comment by brettfo** [comment]
Good find and thank you for fixing it!

**Comment by lgrzywac** [comment]
Is it possible to release 0.5.1 version to NuGet with the fix?

**Comment by brettfo** [comment]
Sure thing.  I've just uploaded the 0.5.1 package to NuGet, but I'm not sure how fast their cache updates.

**Comment by lgrzywac** [comment]
Awesome, thank you!

**Pull request merged**
