### PR TITLE
Make ReferenceCollector use Queue for urls instead of List

### PR DESCRIPTION
**Pull request by sampletext32**

### CODE REVIEW

**Comment by brettfo** [comment]
I'll take the `List<T>` -> `Queue<T>` change, but adding `AddRange` on `ListWithPredicates<T>` doesn't make sense because that type is internal and only ever exposed as `IList<T>`.

**Comment by sampletext32** [comment]
Ok, Updated the PR

**Comment by sampletext32** [comment]
Offtop: I would like to make more contributions to this repository. How can I contact you (discord, email) to ask some questions?

**Comment by brettfo** [comment]
The best way to contact me is email `brett.forsgren` `@` `outlook.com`.  It may sometimes take a few days for me to get to it because I'm getting flooded with kids'-school-from-home-because-of-lockdown stuff, but I will eventually get to it.

**Pull request merged**
